# Generated by Django 6.0.3 on 2026-03-04 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Antibiotic', 'Antibiotic'), ('Analgesic', 'Analgesic'), ('Antifungal', 'Antifungal'), ('Antiseptic', 'Antiseptic'), ('Anesthetic', 'Anesthetic'), ('Vitamin', 'Vitamin'), ('Other', 'Other')], default='Other', max_length=50)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='clinics.clinic')),
            ],
            options={
                'db_table': 'medicines',
                'ordering': ['name'],
            },
        ),
    ]
