# Generated by Django 4.2.10 on 2026-07-12 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0002_alter_appointment_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('color_code', models.CharField(default='#3B82F6', max_length=20)),
                ('buffer_minutes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'treatment_types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recurring_group_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Confirmed', 'Confirmed'), ('Checked-In', 'Checked-In'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show')], default='Scheduled', max_length=20),
        ),
        migrations.CreateModel(
            name='BlockTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('reason', models.CharField(max_length=255)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'DENTIST'}, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'block_times',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='treatment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.treatmenttype'),
        ),
    ]
