# Generated by Django 4.2.10 on 2026-07-12 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_patient_alcohol_consumption_patient_has_diabetes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinics', '0009_clinicsettings_clinicholiday'),
        ('appointments', '0003_treatmenttype_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='insurance_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time_range', models.CharField(blank=True, help_text='e.g. Morning, Afternoon, Any', max_length=50)),
                ('priority', models.CharField(choices=[('EMERGENCY', 'Emergency'), ('VIP', 'VIP'), ('STANDARD', 'Standard')], default='STANDARD', max_length=20)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('NOTIFIED', 'Notified'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='clinics.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='patients.patient')),
                ('preferred_doctor', models.ForeignKey(blank=True, limit_choices_to={'role': 'DENTIST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'waitlist_entries',
                'ordering': [models.Case(models.When(priority='EMERGENCY', then=1), models.When(priority='VIP', then=2), default=3), 'created_at'],
            },
        ),
    ]
