# Generated by Django 4.2.10 on 2026-03-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin (Tresvance)'), ('CLINIC_ADMIN', 'Clinic Admin'), ('DOCTOR', 'Doctor'), ('RECEPTION', 'Receptionist'), ('SUPPORT_AGENT', 'Support Agent (Tresvance)')], default='RECEPTION', max_length=20),
        ),
    ]
