# Generated by Django 4.2.10 on 2026-04-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_bio_user_department_user_license_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='license_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialization',
        ),
        migrations.DeleteModel(
            name='StaffDocument',
        ),
    ]
