# Generated by Django 4.2.10 on 2026-07-08 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_bio_remove_user_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_last_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin (Tresvance)'), ('SUPPORT_AGENT', 'Support Agent (Tresvance)'), ('ADMIN', 'Admin'), ('DENTIST', 'Dentist'), ('HYGIENIST', 'Hygienist/Assistant'), ('RECEPTION', 'Receptionist'), ('ACCOUNT_MANAGER', 'Account Manager')], default='RECEPTION', max_length=20),
        ),
        migrations.CreateModel(
            name='UserPasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_password_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
