# Generated by Django 4.2.10 on 2026-03-04 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='clinic_code',
            field=models.CharField(blank=True, help_text='Short code used for subdomain e.g. LAK', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='subdomain',
            field=models.CharField(blank=True, help_text='Full subdomain e.g. lak.tresdms.com', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_clinics', to=settings.AUTH_USER_MODEL),
        ),
    ]
