# Generated by Django 4.2.10 on 2026-03-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_clinic_clinic_code_clinic_subdomain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='subdomain',
            field=models.CharField(blank=True, help_text='Full subdomain e.g. lak.tresvancehost.com', max_length=100, unique=True),
        ),
    ]
