# Generated by Django 4.2.10 on 2026-03-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_alter_clinic_subdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='subdomain',
            field=models.CharField(blank=True, help_text='Full subdomain e.g. lak.tresvance.com', max_length=100, unique=True),
        ),
    ]
