# Generated by Django 4.2.10 on 2026-03-06 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_alter_clinic_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='is_trial',
            field=models.BooleanField(default=True, help_text='Whether clinic is on trial mode'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='subscription_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly subscription amount in INR (set by Super Admin)', max_digits=10),
        ),
        migrations.AddField(
            model_name='clinic',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, help_text='When current subscription period ends', null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='subscription_status',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('PENDING', 'Pending Payment'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended')], default='TRIAL', help_text='Current subscription status', max_length=20),
        ),
        migrations.AddField(
            model_name='clinic',
            name='trial_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of trial days'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, help_text='When trial ends', null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='trial_start_date',
            field=models.DateTimeField(blank=True, help_text='When trial started', null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in INR', max_digits=10)),
                ('razorpay_order_id', models.CharField(blank=True, help_text='Razorpay order ID', max_length=100, null=True, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, help_text='Razorpay payment ID after successful payment', max_length=100, null=True, unique=True)),
                ('razorpay_signature', models.CharField(blank=True, help_text='Razorpay signature for verification', max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_months', models.PositiveIntegerField(default=1, help_text='Number of months this payment covers')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'clinic_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
