# Generated by Django 4.2.10 on 2026-04-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_bio_remove_user_department_and_more'),
        ('clinics', '0007_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
