# Generated by Django 4.2.10 on 2026-07-12 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_delete_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_hours', models.JSONField(default=dict, help_text='JSON containing daily operating hours. e.g. {"MON": {"start": "09:00", "end": "17:00", "closed": false}}')),
                ('appointment_slot_duration', models.PositiveIntegerField(default=30, help_text='Default slot duration in minutes')),
                ('buffer_time_minutes', models.PositiveIntegerField(default=5, help_text='Default buffer time between appointments in minutes')),
                ('max_appointments_per_day_per_dentist', models.PositiveIntegerField(default=20, help_text='Maximum appointments a dentist can have per day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Clinic Settings',
                'verbose_name_plural': 'Clinic Settings',
                'db_table': 'clinic_settings',
            },
        ),
        migrations.CreateModel(
            name='ClinicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Clinic Holiday',
                'verbose_name_plural': 'Clinic Holidays',
                'db_table': 'clinic_holidays',
                'ordering': ['date'],
                'unique_together': {('clinic', 'date')},
            },
        ),
    ]
