# Generated by Django 4.2.10 on 2026-07-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_clinicsettings_clinicholiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='clinic_code',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='subdomain',
        ),
    ]
