# Generated by Django 4.2.10 on 2026-04-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_staffleave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffLeave',
        ),
    ]
