# Generated by Django 4.2.10 on 2026-03-05 10:18

import apps.patients.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('XRAY', 'X-Ray'), ('CT_SCAN', 'CT Scan'), ('MRI', 'MRI Scan'), ('LAB_REPORT', 'Lab Report'), ('PRESCRIPTION', 'Prescription'), ('CONSENT', 'Consent Form'), ('INSURANCE', 'Insurance Document'), ('PHOTO', 'Clinical Photo'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=apps.patients.models.patient_document_path)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_record', models.ForeignKey(blank=True, help_text='Link to specific visit/record if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='records.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
