# Generated by Django 4.2.10 on 2026-04-10 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_city_patient_emergency_contact_relationship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text='The primary record this patient was merged into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_duplicates', to='patients.patient'),
        ),
    ]
