# Generated by Django 4.2.10 on 2026-04-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_merged_into'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TRANSFERRED', 'Transferred'), ('DECEASED', 'Deceased')], default='ACTIVE', max_length=20),
        ),
    ]
