# Generated by Django 4.2.10 on 2026-04-10 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0005_patient_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('TREATMENT', 'Medical Treatment'), ('DATA_PRIVACY', 'Data Privacy (GDPR/HIPAA)'), ('MARKETING', 'Marketing Communications'), ('TELEHEALTH', 'Telehealth Consent')], max_length=20)),
                ('status', models.CharField(choices=[('GRANTED', 'Granted'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='GRANTED', max_length=15)),
                ('is_signed', models.BooleanField(default=False)),
                ('signer_name', models.CharField(help_text='Full name as typed by signer', max_length=150)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('witness_name', models.CharField(blank=True, help_text='Clinic staff who witnessed sign-off', max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('document', models.ForeignKey(blank=True, help_text='Reference to scanned physical document if available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_consents', to='patients.patientdocument')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_consents',
                'ordering': ['-signed_at'],
            },
        ),
    ]
