# Generated by Django 4.2.10 on 2026-04-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patientconsent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='referring_source',
        ),
        migrations.AddField(
            model_name='patient',
            name='is_high_risk',
            field=models.BooleanField(default=False, help_text='Patient with critical medical complications'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_vip',
            field=models.BooleanField(default=False, help_text='Priority patient for scheduling'),
        ),
        migrations.AddField(
            model_name='patient',
            name='risk_details',
            field=models.TextField(blank=True, help_text='Specific details about medical risks'),
        ),
    ]
