# Generated by Django 4.2.10 on 2026-04-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_patient_referring_source_patient_is_high_risk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='referring_source',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
