# Generated by Django 4.2.10 on 2026-06-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patient_referring_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TRANSFERRED', 'Transferred'), ('DECEASED', 'Deceased'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20),
        ),
    ]
