# Generated by Django 4.2.10 on 2026-07-09 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='alcohol_consumption',
            field=models.CharField(choices=[('NONE', 'None'), ('OCCASIONAL', 'Occasional'), ('REGULAR', 'Regular'), ('HEAVY', 'Heavy')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_heart_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_hypertension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_pregnant',
            field=models.BooleanField(default=False, help_text='For female patients'),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_conditions',
            field=models.TextField(blank=True, help_text='List any other medical conditions'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pregnancy_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='smoker_status',
            field=models.CharField(choices=[('NEVER', 'Never Smoked'), ('FORMER', 'Former Smoker'), ('CURRENT', 'Current Smoker')], default='NEVER', max_length=20),
        ),
        migrations.CreateModel(
            name='PatientMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=150)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_medications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.CharField(max_length=150)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('LIFE_THREATENING', 'Life-Threatening')], default='MILD', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_allergies', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_allergies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DentalSurgeryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=200)),
                ('procedure_date', models.DateField(blank=True, null=True)),
                ('complications', models.TextField(blank=True)),
                ('dentist_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_surgeries', to='patients.patient')),
            ],
            options={
                'db_table': 'dental_surgery_history',
                'ordering': ['-procedure_date'],
            },
        ),
    ]
