# Generated by Django 4.2.10 on 2026-04-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_treatmentplan_remove_medicalrecord_treatment_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecordversion',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='medicalrecordversion',
            name='medical_record',
        ),
        migrations.RemoveField(
            model_name='treatmentplan',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='treatmentplan',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='treatmentplanitem',
            name='treatment_plan',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='is_signed',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='signed_at',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='signed_by',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='treatment_plan_summary',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ClinicalNote',
        ),
        migrations.DeleteModel(
            name='MedicalRecordVersion',
        ),
        migrations.DeleteModel(
            name='TreatmentPlan',
        ),
        migrations.DeleteModel(
            name='TreatmentPlanItem',
        ),
    ]
