# Generated by Django 4.2.10 on 2026-07-09 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0005_alter_medicalrecord_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='periodontal_status',
            field=models.TextField(blank=True, help_text='Detailed periodontal and gum health status'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClinicalNoteVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_snapshot', models.TextField()),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_modifications', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='records.clinicalnote')),
            ],
            options={
                'db_table': 'clinical_note_versions',
                'ordering': ['-modified_at'],
            },
        ),
    ]
